### ISSUE TITLE
Great, don't stop!

### ISSUE THREAD

**Issue by Codcore** [waterlink/active_record.cr#2]
I'm going to use it with [Amethyst](https://github.com/Codcore/Amethyst). Are you going to write adapter for postgres?

**Comment by waterlink** [comment]
Yes, it is on todo list and on my radar :)

**Comment by sdogruyol** [comment]
I'm also waiting for the Postgres adapter. Is there anything i can do for helping with that?

**Comment by waterlink** [comment]
@Sdogruyol Hi, you can look at the `NullAdapter` implementation and on abstract `Adapter` protocol and try to implement postgres adapter as a separate library :) And of course report all the problems/issues/missing-feature you see with how `Adapter` should work here :)

**Comment by artintal** [comment]
Awesome! I understand that this is not the same as active record for rails, but out of curiosity, any reason you named the methods read and index rather than find and all? Just preference? Any opinions against me sending a PR for a name change for ease of migration from Rails?

**Comment by waterlink** [comment]
@artintal Think `CRUD`: `C = create; R = read; U = update; d = delete.`.

I have very strong opinion about rails and you better not to hear me about it.

If you can convince me about `read => find` without resorting to mentioning rails, then you might try.

On the other hand, this is already quite bad from view of Object-Oriented design. True Active Record Pattern should have only `create`, `update` and `delete` method out of `CRUD`. And all querying should go to entirely different object. And I might as well consider such a thing.

There might be even notion of `read(id) => get(id)` or `... => fetch(id)`, WDYT?

**Comment by lustrousgorilla** [comment]
@waterlink Why does remaining true to the design pattern matter at all? 

Admittedly, I'm biased and think that OO design has increasingly become a cargo cult - but there's an extremely large and successful community using Rails' ActiveRecord and changing the convention (for very dubious gain) can only hurt adoption of your implementation.

**Comment by waterlink** [comment]
@lustrousgorilla True. Very good point.

Let me think.

**On the one hand**:

I have enough `rails/active_record` experience to say that it works perfectly for simple domain models (like blog, or basecamp - which is just a bit more complicated blog), but Active Record pattern is not scalable enough to be used for complex business domains. Instead, when your domain becomes to complicated, you drop Active Record in favor of Data Mapper + Domain Objects.

Well, I do not know OO from books (I did read them, but already after having certain level of skill in it), I know it from experience with huge legacy systems, that means it is not something that I just blindly believe in - it is something that I have built up as a skill. And my skill says, that if I want to build whatever more complicated than 2 times blog app, I will not use Active Record pattern. If I am forced to use it, because it is already there, I will wrap active record objects in my own domain objects and encapsulate them entirely, treating them just like raw data types (like `Fixnum`, `String`, etc) and putting all behavior in Domain Objects.

**On the other hand**:

Your point is extremely right. And if I agree with you and make very familiar interfaces to what we see today in `rails/active_record` the adoption of this library will be quite high, which can actually beef up adoption of crystal lang itself if you combine it with `Amethyst` efforts. Which in itself will allow to grow community of the language and as a result **make language mature faster**.

**And third point**:

Which is more important, since the question is about renaming `read => find` to make adoption easier. It is just renaming method and it does not make code less clean in any way. Which means we can do it easily. @lustrousgorilla @artintal Are you up to making a PR?

---

And last but not least:

Lets assume that I am convinced in making this library the most adoptable to put effort in growing community (which I am almost already convinced :)), then should we just copy how `rails/active_record` works, or should we actually try to make it better, simpler and cleaner, on top of being well-adoptable?

**Comment by waterlink** [comment]
WDYT?

**Comment by lustrousgorilla** [comment]
That's a difficult question. Making it better, simpler, and cleaner would obviously be a good thing, but I think any refactoring efforts should be aimed more at the internals than at the interface. Given @Codcore intends to use this in Amethyst and that's likely to be the primary driver of adoption, I think the amount of deviation between the interfaces of your library and rails/active_record should mirror the amount of deviation between Amethyst and Rails. From my understanding, Amethyst doesn't aim to be identical, just as familiar as possible. That strikes me as the ideal guiding principle moving forward.

**Comment by artintal** [comment]
I would be happy to do a PR later tonight (I agree that it will be a pretty quick and easy change). I agree with @lustrousgorilla in that you can probably make a lot of improvements to the internals vs rails/ActiveRecord due to there being no historical baggage in this repo but I would maintain the interface as much as possible. Personally, I do not know enough about the internal workings of rails/ActiveRecord to even make a ballpark guess on how much improvement there is to be made. 

I would also add that the differences between Amethyst and Rails, at least from the outside, appear to be more about being a temporary scaffold holding Amethyst together while it is being built and less intentional design decisions built to last. I will leave agreement or disagreement on that note to @Codcore since he is the Amethyst developer.

**Comment by waterlink** [comment]
Well, the biggest problem, I do not like public interface, ie: lack of encapsulation and being bloated. It often drives you to put much more responsibility into one object, rather than having multiple collaborating objects. I am that kind of guy: "You see here 1 method. I see here 3 classes.". And I am not gonna talk about coupling :)

But I am convinced now.

That means that we need to change goal of this library stated in README and repo description, because it basically states: "do not confuse with Ruby's active_record"..

**Comment by artintal** [comment]
Agreed. I can add that to a separate PR tonight if someone else hasn't already gotten to it.

**Comment by sfcgeorge** [comment]
Crystal should be good for big projects due to its speed. But at this stage nobody will trust it for big projects, they'll want to build small demo projects with it as fast as possible. So a "better" AR would be a nice later goal, but possibly nobody needs that _yet_. 

RailsAR as it is has been used loads quite successfully. Perhaps best for small–medium projects, but there are lots of those. So copying for familiarity seems reasonable. But renaming a method here and there where it makes more sense seems fine. Look at Crystal itself—the `include?` method that is grammatically wrong in Ruby has been improved to `includes?`. In this case `find` sounds like a search function so I always found it weird that it raises. I don't think `read` is any better as it sounds like an IO method to load the contents into memory. However I do like your `get` suggestion, that makes a lot of sense to me! How about calling it `get` and adding an alias to `find`?

I wonder if it's possible to write a "better" core AR implementation that works for big projects, plus a RailsAR wrapper / DSL for when you just want short / readable / familiar code for a small project that doesn't need much modularity.

Or if you can think of a better DSL than RailsAR that's equally short and readable for small projects but also works for large ones then that would be cool! But given the time RailsAR had to evolve and how hard naming things is I don't think this would be easy.

**Comment by waterlink** [comment]
@sfcgeorge I see those as a viable choice:
- `Model.get(id)`
- `Model.fetch(id)`
- `Model[id]`

**Comment by sdogruyol** [comment]
_Model.get(id)_ :+1:

**Comment by sfcgeorge** [comment]
@waterlink Oh wow the square brackets is such an obvious method it seems perfect! Because you expect a wrong array index to raise, and this is in effect a database index. I would love that in addition to a wordy method perhaps?

I prefer `get` to `fetch` as it's shorter and relates quite nicely to the get action: GET `/users/42` runs `Users.get(42)`. Also `fetch` is so close to `find` maybe it would be confusing? Though `fetch` makes more sense than `find`: "Fetch me X from the cupboard" rather than "Find if we have any of X in the cupboard?" :)

**Comment by waterlink** [comment]
I like `get` with alias `[]`.

**Comment by waterlink** [comment]
Changed it :)

Now I will just fix `mysql_adapter.cr` and start working on `postgres_adapter.cr`

**Comment by waterlink** [comment]
Fixed `mysql_adapter.cr` to implement `get` instead of `find`.

**Comment by sfcgeorge** [comment]
Aah so great :D thanks for your work.

**Comment by sdogruyol** [comment]
Great :+1:

**Comment by waterlink** [comment]
So here you go: https://github.com/waterlink/postgres_adapter.cr
