### ISSUE TITLE
TypeCastError when trying to get

### ISSUE THREAD

**Issue by sdogruyol** [waterlink/active_record.cr#23]
Running this

``` crystal
class MenuItem < ActiveRecord::Model
  adapter postgres

  primary(id :: Int)
  field(seq :: Int)
  field(name :: String)
end

MenuItem.get(1)
```

Gives the following TypeCastError

```
cast to MenuItem failed (TypeCastError)
[4356167138] *CallStack::unwind:Array(Pointer(Void)) +82
[4356167041] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4356167000] *CallStack::new:CallStack +40
[4356205665] *Exception@Exception#initialize<TypeCastError, String>:CallStack +33
[4356205597] *TypeCastError#initialize<TypeCastError, String>:CallStack +29
[4356205532] *TypeCastError::new<String>:TypeCastError +92
[4356243251] *MenuItem@ActiveRecord::Model::get<Int32>:MenuItem +163
[4356139493] __crystal_main +26229
[4356148723] main +35
```

Crystal 0.9.0 (Sun Oct 18 19:49:05 UTC 2015)

**Comment by waterlink** [comment]
That happens in case when record is not found. I assume it tries to cast `nil` or `Model::Null` type or something. I think this case is simply not handled currently and there is no spec for that.

So what do you think is the expected behavior, when `get(id)` can't find the record with such id? The options I see:
- raise specific error (like ruby's AR does),
- return `MenuItem::Null` object, which is already defined for each model.

**Comment by sdogruyol** [comment]
@waterlink I think raising a specific error like AR is good :+1: 

Something like

`ActiveRecord::RecordNotFound: Couldn't find MenuItem with 'id'=1`

**Comment by sdogruyol** [comment]
Meanwhile if you guide me i can try to implement this

**Comment by waterlink** [comment]
Look at this method: https://github.com/waterlink/active_record.cr/blob/master/src/model.cr#L191-L193

You will see that it first calls to adapter's `#get` and then passes the result to `#build` and then typecasts to `self`.

Currently:
- adapter's `#get` returns `nil` when record is not found
- `#build(fields : Hash)` - builds correct model instance
- `#build(fields : Nil)` - returns `YourModel::Null` instance
- and `YourModel::Null` apparently can not be typecasted to `self`

What you want is to make either `#build(fields : Nil)` or `#get` before calling to `#build` fail with this error. Since `#build` is used only from `#get` - it should be safe to raise from `#build(fields : Nil)`. Additionally there is a chance `YourModel::Null` can be removed now?

**Comment by waterlink** [comment]
And of course don't forget to create a test for that ;)

**Comment by sdogruyol** [comment]
Thanks for the info :+1: I'll try to solve this

**Comment by waterlink** [comment]
All core tests are currently in `spec/active_record_spec.cr` - those act as acceptance tests for adapters.

**Comment by sdogruyol** [comment]
Meanwhile is there anything like this in Crystal. I'm trying to test if it raises

``` crystal
Person.get(person.id).should raise_error
```

**Comment by sdogruyol** [comment]
Meanwhile i've seen this https://github.com/waterlink/spec2.cr/blob/8b438c18c03f1074027179106e7876a7c56fdcba/spec/matchers_spec.cr#L36-L41

**Comment by waterlink** [comment]
``` crystal
expect_raises(ActiveRecord::RecordNotFoundError, "Couldn't find MenuItem with 'id'=7892") do
  Person.get(person.id)
end
```

**Comment by waterlink** [comment]
> Meanwhile i've seen this https://github.com/waterlink/spec2.cr/blob/8b438c18c03f1074027179106e7876a7c56fdcba/spec/matchers_spec.cr#L36-L41

Yeah, this is my `spec2`. I will soon start converting my projects to it :)

**Comment by sdogruyol** [comment]
It looks great :+1: Feels like more `rspec`ish :100:
